master:
  stage: deploy
  only:
    - master
  script:
    - cd /home/deployer/laravel-example
    - git pull
    - composer install
    - php artisan deploy
    - touch test3.txt

dev:
  stage: deploy
  only:
    - dev
  script:
    - cd /home/deployer
    - touch test.txt
