before_script:
  - echo "Before script"
  - cd /root/laravel-example #your project path
  - git pull
  - composer install
deploying:
  stage: deploy
  script:
    - echo "Deployed"
    - php artisan deploy
